const key='nspa-2026-capacity-v1';
const fields=['priority','next-action','evidence','owner','target-date','stop'];
const domains=['scope','prompt','rubric','privacy','policy','improve'];
const levels=['Unassessed','Explore','Practice','Apply','Improve'];
const status=document.querySelector('#save-status');
function snapshot(){const data={ratings:{},plan:{}};domains.forEach(d=>data.ratings[d]=document.querySelector(`input[name="${d}"]:checked`)?.value||'');fields.forEach(id=>data.plan[id]=document.getElementById(id).value);return data;}
function summarize(){const n=Object.values(snapshot().ratings).filter(Boolean).length;document.querySelector('#matrix-status').textContent=`${n} of 6 capacities assessed. Choose one priority; no overall score is calculated.`;}
function save(){try{localStorage.setItem(key,JSON.stringify(snapshot()));status.textContent='Saved in this browser.';}catch{status.textContent='Browser storage is unavailable. Export your plan before leaving.';}summarize();}
try{const data=JSON.parse(localStorage.getItem(key)||'null');if(data){domains.forEach(d=>{const v=String(data.ratings?.[d]||'');if(['1','2','3','4'].includes(v))document.querySelector(`input[name="${d}"][value="${v}"]`).checked=true;});fields.forEach(id=>{const v=data.plan?.[id];if(typeof v==='string')document.getElementById(id).value=v;});}}catch{status.textContent='Saved answers could not be loaded. Export your plan to keep a copy.';}
document.querySelectorAll('.capacity-table input,.plan-form input,.plan-form textarea,.plan-form select').forEach(el=>el.addEventListener('input',save));
document.querySelectorAll('[data-clear]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll(`input[name="${button.dataset.clear}"]`).forEach(el=>el.checked=false);save();}));
document.querySelector('#export-plan').addEventListener('click',()=>{const data=snapshot();let text='NSPA 2026 — My capacity and 30-day action plan\nSelf-reflection, not certification\nhttps://mguhlin.github.io/nspa/2026/capacity-matrix.html\n\n';domains.forEach(d=>{const row=document.querySelector(`input[name="${d}"]`).closest('tr');const checked=row.querySelector('input:checked');text+=row.querySelector('th strong').textContent+': '+levels[Number(data.ratings[d])||0]+'\n';if(checked)text+=checked.parentElement.querySelector('span').textContent.replace(levels[Number(data.ratings[d])], '').trim()+'\n';text+='Resources: '+[...row.querySelectorAll('th a')].map(a=>a.href).join(' | ')+'\n\n';});fields.forEach(id=>{const el=document.getElementById(id);const label=el.closest('label').childNodes[0].textContent.trim();const value=id==='priority'?el.options[el.selectedIndex].text:data.plan[id];text+=label+': '+value+'\n\n';});const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nspa-capacity-plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Plan exported to a text file.';});
document.querySelector('#print-plan').addEventListener('click',()=>window.print());
document.querySelector('#reset-plan').addEventListener('click',()=>{if(!window.confirm('Clear all ratings and plan answers saved in this browser? Export first if you want to keep a copy.'))return;document.querySelectorAll('.capacity-table input').forEach(el=>el.checked=false);fields.forEach(id=>document.getElementById(id).value='');try{localStorage.removeItem(key);}catch{}summarize();status.textContent='Saved answers cleared.';});
summarize();

window.addEventListener('beforeprint',()=>{fields.forEach(id=>{const el=document.getElementById(id);let output=el.parentElement.querySelector('.print-value');if(!output){output=document.createElement('div');output.className='print-value';el.after(output);}output.textContent=(id==='priority'?el.options[el.selectedIndex].text:el.value)||'Not entered';});});
