const key='nspa-2026-checklist-v2';
const fields=['priority','next-action','evidence','owner','target-date','stop'];
const rows=[...document.querySelectorAll('[data-item]')];
const ratings=['Not marked','Ready to learn','In progress','Ready to go'];
const status=document.querySelector('#save-status');
function snapshot(){return {items:Object.fromEntries(rows.map(row=>[row.dataset.item,{rating:row.querySelector('input:checked')?.value||'',note:row.querySelector('textarea').value}])),plan:Object.fromEntries(fields.map(id=>[id,document.getElementById(id).value]))};}
function summarize(){const n=rows.filter(row=>row.querySelector('input:checked')).length;document.querySelector('#matrix-status').textContent=`${n} of ${rows.length} items marked. Choose one next step; there is no overall score.`;}
function save(){try{localStorage.setItem(key,JSON.stringify(snapshot()));status.textContent='Saved in this browser.';}catch{status.textContent='Browser storage is unavailable. Export your plan before leaving.';}summarize();}
try{const data=JSON.parse(localStorage.getItem(key)||'null');if(data){rows.forEach(row=>{const item=data.items?.[row.dataset.item];if(['1','2','3'].includes(item?.rating))row.querySelector(`input[value="${item.rating}"]`).checked=true;if(typeof item?.note==='string')row.querySelector('textarea').value=item.note;});fields.forEach(id=>{if(typeof data.plan?.[id]==='string')document.getElementById(id).value=data.plan[id];});}else{const previous=JSON.parse(localStorage.getItem('nspa-2026-capacity-v1')||'null');if(previous){fields.forEach(id=>{if(typeof previous.plan?.[id]==='string')document.getElementById(id).value=previous.plan[id];});status.textContent='Your earlier action plan is shown below. Mark the new checklist items individually; the old level ratings have not been converted.';}}}catch{status.textContent='Saved answers could not be loaded. Export your work to keep a copy.';}
document.querySelectorAll('.indicator-table input,.indicator-table textarea,.plan-form input,.plan-form textarea,.plan-form select').forEach(el=>el.addEventListener('input',save));
document.querySelectorAll('[data-clear]').forEach(button=>button.addEventListener('click',()=>{button.closest('tr').querySelectorAll('input').forEach(el=>el.checked=false);save();}));
document.querySelector('#export-plan').addEventListener('click',()=>{let text='NSPA 2026 - My capacity checklist and next step\nhttps://mguhlin.github.io/nspa/2026/capacity-matrix.html\n\n';document.querySelectorAll('.checklist-section').forEach(section=>{text+=section.querySelector('h2').textContent+'\n';section.querySelectorAll('[data-item]').forEach(row=>{text+=row.querySelector('th').textContent+'\n'+ratings[Number(row.querySelector('input:checked')?.value)||0]+'\nNotes: '+row.querySelector('textarea').value+'\n\n';});text+='Resources: '+[...section.querySelectorAll('.checklist-resources a')].map(a=>a.href).join(' | ')+'\n\n';});fields.forEach(id=>{const el=document.getElementById(id);text+=el.closest('label').childNodes[0].textContent.trim()+': '+(id==='priority'?el.options[el.selectedIndex].text:el.value)+'\n\n';});const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nspa-capacity-plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Checklist and plan exported.';});
document.querySelector('#print-plan').addEventListener('click',()=>window.print());
document.querySelector('#reset-plan').addEventListener('click',()=>{if(!window.confirm('Clear all checklist ratings, notes, and action plan answers saved in this browser? Export first to keep a copy.'))return;rows.forEach(row=>{row.querySelectorAll('input').forEach(el=>el.checked=false);row.querySelector('textarea').value='';});fields.forEach(id=>document.getElementById(id).value='');try{localStorage.removeItem(key);localStorage.removeItem('nspa-2026-capacity-v1');}catch{}summarize();status.textContent='Saved answers cleared.';});
window.addEventListener('beforeprint',()=>{document.querySelectorAll('.notes-cell textarea,.plan-form input,.plan-form textarea,.plan-form select').forEach(el=>{let output=el.parentElement.querySelector('.print-value');if(!output){output=document.createElement('div');output.className='print-value';el.after(output);}output.textContent=el.tagName==='SELECT'?el.options[el.selectedIndex].text:el.value;});});
summarize();
