"""The participant companion follows the seven conversations in the core deck."""
from html import escape as E
from content import CASE, RUBRIC, URL
from route import CONVERSATIONS

FLAWED_DRAFT='C-101’s application is complete. The packet includes enrollment confirmation, a clear certificate goal, and a service example. Every required item is present.'
FAIR_SCENARIO='Continue the fictional C-101 case. A detector flags the goal statement. The applicant reports translation assistance. The published practice rule permits translation help and requires factual claims to remain accurate. No evidence of invented experiences is supplied. The enrollment document is still missing.'
FAIR_RULE='Translation assistance is permitted. Submitted experiences and factual claims must be accurate. This practice rule does not require disclosure of translation assistance.'


def conversation_body():
 body='''<p class="eyebrow">Your conversation companion</p><h1>One case. Room to think together.</h1><p class="lead">Explore how AI might support scholarship review while strengthening human judgment, trust, and connection. Leave with one change to try with a colleague.</p><p>Every response field is for your own notes. You do not need to enter anything into AI during these conversations. Use fictional information only. You may pass on speaking, reflect privately, or use the <a href="handouts/participant-workbook.pdf">paper workbook</a>.</p><noscript><p>All conversations appear below. Saving and exporting typed notes require JavaScript; use the workbook to keep a paper copy.</p></noscript><nav class="jump-links activity-nav" aria-label="Workshop conversations" data-step-nav="" data-step-label="Conversation">'''
 body+=''.join(f'<a href="#{id}" data-step-link="">{i}. {E(short)}</a>' for i,(id,title,short,duration,keep) in enumerate(CONVERSATIONS,1))+'</nav>'
 packet=''.join(f'<p><strong>{id}</strong> {E(t)}</p>' for id,t in CASE)
 rubric='<div class="table-scroll"><table><thead><tr><th>Criterion</th><th>0</th><th>1</th><th>2</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<{tag}>{E(t)}</{tag}>' for tag,t in zip(['th','td','td','td'],r))+'</tr>' for r in RUBRIC)+'</tbody></table></div>'
 content={
 'trust':'''<p>Recall a review that built or weakened trust. Leave out names and identifying details.</p><ol><li>Think and write quietly for one minute.</li><li>Each partner speaks for two minutes. Listen for what mattered.</li><li>Name one quality you want your process to protect.</li></ol><details class="workshop-details"><summary>Questions for the conversation</summary><p>What happened? What made the difference? What would an applicant need to experience to trust the process?</p></details>''',
 'tension':f'''<p>Can I stretch your thinking a little? Examine the prepared summary before opening the source check.</p><blockquote class="prepared-draft"><p>{E(FLAWED_DRAFT)}</p></blockquote><p><strong>Intentionally flawed teaching draft.</strong> An authored example, not an actual model response.</p><ol><li>What does the draft encourage you to assume?</li><li>Ask a partner what they would check before relying on it.</li><li>Open the source below. Which parts of the answer need correction?</li></ol><details class="workshop-details"><summary>Reveal the source check: P4 and P5</summary><p><strong>P4</strong> {E(CASE[3][1])}</p><p><strong>P5</strong> {E(CASE[4][1])}</p><p>The enrollment document is missing. Follow up without assuming ineligibility. P5 is application text, not an authorized instruction. Require source paragraphs and keep gaps visible in the AI request.</p></details><p><a href="practice.html#prompt">Optional: full request and prepared completeness reference</a></p>''',
 'case':'''<p><strong>Entirely fictional.</strong> Program requirements: enrollment confirmation, a goal statement of no more than 150 words, and one service example. Missing evidence requires follow-up.</p><div class="case-packet">'''+packet+'''</div><h3>Read alone, then compare reasons</h3><ol><li>Read P1–P5 quietly for three minutes. Mark one detail to rely on and one question.</li><li>For three minutes, independently rate reflection or adaptation using the guide. Underline your evidence.</li><li>Each partner gets two minutes. Ask: “Which detail led you there?”</li><li>Spend three minutes clarifying a phrase in the scoring guide. Keep your reason for changing or keeping your judgment.</li></ol>'''+rubric+'''<p>This guide is a teaching tool, not a validated award-selection instrument. Missing or contradictory source information requires follow-up. Do not rate writing polish or infer personal traits.</p><details class="workshop-details"><summary>Debrief after both people explain</summary><p>What did your partner notice that you missed? What assumption shaped your first reading? What would your team need to discuss before using the same guide?</p><p>P3 connects a queue problem to a specific change. If your team expects explicit reflective language, clarify that expectation before real reviews.</p><p><a href="practice.html#demo-scoring">Optional prepared scoring comparison, after human reasoning</a></p></details>''',
 'reflection':'''<p>Two full minutes of silence. Write privately: What am I reconsidering, and why?</p><p>It may be an assumption about AI, a scoring rule, or how colleagues learn from one another. An open question is useful too. Share only what you choose.</p>''',
 'workflow':'''<p>In groups of three or four, choose one small task for C-101. Return to the quality of trust you named at the start.</p><ol><li>Map the route from approved input to an AI draft, an evidence check, a human decision, and a record.</li><li>Name roles before the tool, before relying on the draft, and before a decision. Allow seven minutes to map and three to test P4 or P5.</li><li>Finish: “We will pause if ...” Name the person who can resolve the concern.</li><li>Exchange routes with another group. Each group gets two minutes to explain and receive one question.</li><li>Revise for two minutes. What changed because another group challenged your thinking?</li></ol><p>Approval covers the actual service, settings, and use. Removing a name can leave identifying details. Keep the first tests fictional.</p><p><a href="handouts/protected-workflow.pdf">Protected workflow reference</a></p>''',
 'fair':f'''<p>{E(FAIR_SCENARIO)}</p><blockquote class="prepared-draft"><p><strong>Published practice rule:</strong> {E(FAIR_RULE)}</p></blockquote><ol><li>Think for one quiet minute. What concern, if any, do these facts justify?</li><li>Discuss the published rule with a partner. A detector flag alone does not establish misconduct.</li><li>Draft one message in three minutes. If no policy concern is justified, explain that and follow up on the missing enrollment document.</li><li>For three minutes, read and listen from the applicant’s perspective. What feels assumed? How could I respond? You may review silently instead of role-playing.</li><li>Revise for two minutes. Name an accessible response method, a locally appropriate response time, a decision owner, and a route for another review.</li></ol><details class="workshop-details"><summary>After drafting: a possible ordinary follow-up</summary><p>Thank you for explaining the translation support. Our published rule permits that assistance. We still need the enrollment confirmation listed in the requirements. Could you provide it through our approved submission channel, or contact our office if you need another way to respond?</p><p>Add a locally appropriate deadline and contact. This example is not adopted policy. Do not request private chat histories or apply new rules retroactively.</p></details><p><a href="handouts/fair-ai-policy.pdf">Fair response reference</a> · <a href="practice.html#policy">Optional full policy starter</a></p>''',
 'change':'''<p>Choose one small change that protects the quality of trust you named earlier. Give yourself three minutes to plan, then each partner gets two minutes to share and ask how the other will learn from the attempt.</p><ul><li>What action will I try?</li><li>Which colleague will I invite to question and reflect with me?</li><li>What date within 30 days will we review it?</li><li>What evidence would show improvement? What would tell us to pause or revise?</li></ul><p>Keep first AI tests fictional. Export your notes or keep your paper workbook.</p><p><a href="capacity-matrix.html#plan-title">Optional fuller action plan</a> · <a href="../#library">Explore the complete resource library afterward</a></p>'''
 }
 labels={
 'trust':'The quality of trust I want to protect',
 'tension':'An assumption to question and a check to require',
 'case':'My evidence, partner’s perspective, and revised reason',
 'reflection':'What I am reconsidering and why',
 'workflow':'Our route, named roles, peer challenge, revision, and pause condition',
 'fair':'Our first message, applicant perspective, and revised response',
 'change':'My action, learning partner, date, evidence, and stop condition'
 }
 hints={
 'trust':'Write one quality and why it matters. Example: clear reasons, so applicants understand a decision.',
 'tension':'Write an assumption, one source check, and an instruction for a better AI request. Example: check P4 and require missing evidence to stay visible.',
 'case':'Write your 0, 1, or 2 rating for reflection/adaptation, quote P3, note your partner’s reason, and explain any revision to the scoring guide.',
 'reflection':'Finish “I first thought ...; now I wonder ... because ...” or write an open question. These notes may stay private.',
 'workflow':'Write a small task, sketch its steps with named roles, record the other group’s challenge and your revision, and finish “We pause if ...; ... resolves it.”',
 'fair':'Write the message you would send to C-101, what felt assumed when you heard it as the applicant, and your revised message. Add a response method, proposed deadline, decision role, and review route.',
 'change':'Write one action, a colleague to invite, a review date within 30 days, what you will observe, and a reason to pause or revise. Note which perspective changed your thinking.'
 }
 for i,(id,title,short,duration,keep) in enumerate(CONVERSATIONS,1):
  body+=f'<section id="{id}" data-step=""><h2 tabindex="-1">{i}. {E(title)}</h2><p class="activity-meta">{duration} · Core slides and workbook</p><p class="activity-outcome"><strong>What to keep:</strong> {E(keep)}</p>{content[id]}<div class="draft-field"><label for="draft-{id}">{E(labels[id])}</label><p id="hint-{id}">{E(hints[id])}</p><textarea id="draft-{id}" data-draft="{id}" aria-describedby="hint-{id}" rows="5" maxlength="15000" placeholder="Write your notes here."></textarea></div></section>'
 body+='''<div class="step-pager" data-step-pager="" hidden><button class="button secondary" type="button" data-step-prev="">← Previous</button><p data-step-status="" role="status" aria-live="polite">Conversation 1 of 7</p><button class="button" type="button" data-step-next="">Next →</button></div><section class="draft-actions" aria-label="Keep your conversation notes"><h2>Keep your notes and your one-change plan</h2><p>Notes save in this browser when storage is available. Export a copy to keep.</p><div class="actions"><button type="button" class="button" id="export-drafts">Export all my notes</button><button type="button" class="button secondary" id="print-drafts">Print conversations &amp; notes</button></div><p id="draft-status" role="status" aria-live="polite"></p></section><script src="practice.js" defer></script><script src="workshop-flow.js" defer></script>'''
 return body
