"""Offline manual worksheet adapted from mglearn/tcea PROTECT category data."""
from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[2]
SOURCE=Path(__file__).parent/'offline-inputs/protect_rubric_v2/data/protect-v2.json'
def build():
 data=json.loads(SOURCE.read_text());out=ROOT/'2026/offline/resources/protect';out.mkdir(parents=True,exist_ok=True);E=html.escape
 body='''<p class="eyebrow">NSPA offline edition · Manual review</p><h1>PROTECT privacy review worksheet</h1><p>Use the seven PROTECT categories to examine a tool’s published privacy and security documents. Record evidence and unanswered questions before your organization decides what is suitable.</p><p class="notice">Adapted from the school-oriented PROTECT Rubric v2.0 in mglearn/tcea. Check how each category applies to your scholarship program and applicant ages. This worksheet does not determine legal compliance or grant approval. No keyword scoring or AI service is used.</p><p>Use public vendor documentation or fictional examples here. All work stays in this browser. Export JSON to keep an editable copy; import it to continue later. Text and CSV exports and browser Print / Save as PDF work offline. DOCX and image export are not included in this manual edition.</p><div class="actions"><button class="button" data-export="json">Export editable JSON</button><button class="button" data-export="txt">Export text report</button><button class="button" data-export="csv">Export CSV</button><button class="button secondary" onclick="window.print()">Print or save as PDF</button></div><p><label>Restore a saved review <input id="import-review" type="file" accept=".json,application/json"></label></p><p id="status" role="status"></p><section><h2>Review details</h2>'''
 for id,label in [('vendor','Vendor or tool'),('reviewer','Reviewer or role'),('date','Review date'),('documents','Documents reviewed and their dates')]:body+=f'<label for="{id}">{label}</label><textarea id="{id}" data-field rows="2"></textarea>'
 body+='</section><section><h2>Choose a rating only after reviewing evidence</h2><p><strong>0:</strong> absent, vague, or contradictory. <strong>1:</strong> partly addressed, with material gaps. <strong>2:</strong> clear, specific, and verifiable. Leave an item <strong>not reviewed</strong> when you have not assessed it, or mark <strong>not applicable</strong> and explain why.</p><p id="progress" role="status"></p></section>'
 questions=[
 'What process lets applicants access or correct information, request deletion, or obtain a copy? Who handles requests, on what timeline, and how are applicable parent or guardian rights handled?',
 'What is kept, for how long, and for what purpose? What happens at account closure or contract termination, including backups and copies held by others?',
 'Can people decline optional uses? What do the terms say about advertising, sale or sharing, profiling, and using submitted information to train models?',
 'Which information is collected, why, where is it hosted, and which other organizations receive it? How are people told about material policy changes?',
 'What documentation describes encryption, access controls, incident handling, and independent security review? Which claims still need confirmation?',
 'How does the tool handle the ages and consent requirements relevant to your program? Who must approve use, and what alternatives exist when approval is absent?',
 'Which subcontractors or service providers receive information? What restrictions follow the data, and how are changes, objections, and deletion requests handled?']
 for c,question in zip(data['categories'],questions):
  n=c['number'];body+=f'<section class="review-category"><h2>{c["code"]} · {E(c["name"])}</h2><p>{E(question)}</p><label for="score-{n}">Your rating</label><select id="score-{n}" data-field data-score><option value="">Not reviewed</option><option value="0">0 — Absent or unclear</option><option value="1">1 — Partial</option><option value="2">2 — Clear and verifiable</option><option value="NA">Not applicable — explain below</option></select><label for="evidence-{n}">Evidence and source location</label><textarea id="evidence-{n}" data-field></textarea><label for="gap-{n}">Gaps, questions, or reason this does not apply</label><textarea id="gap-{n}" data-field></textarea></section>'
 body+='<section><h2>Human review and next steps</h2><p>A total is only a summary of the ratings you entered. It does not authorize use. Record unresolved questions, the decision owner, and any required review.</p>'
 for id,label in [('conditions','Conditions and open questions'),('owner','Decision owner and next action'),('recheck','Date and reason to review again')]:body+=f'<label for="{id}">{label}</label><textarea id="{id}" data-field></textarea>'
 body+='</section><p>Source for later reference: mglearn.github.io/tcea/protect_rubric_v2/ · Categories retained; questions and scoring presentation adapted for a manual NSPA worksheet. Source snapshot: September 24, 2026.</p>'
 page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PROTECT manual privacy worksheet | NSPA offline</title><link rel="stylesheet" href="../../offline.css"><style>label{display:block;margin-top:18px}select{display:block;margin:10px 0}.review-category{border-top:4px solid #007681;padding-top:12px}.print-value{display:none}@media print{.print-value{display:block;white-space:pre-wrap}input,select,textarea{display:none}.review-category{break-inside:auto}h2{break-after:avoid}}</style></head><body><header><nav><a href="../../index.html">Offline workshop</a><a href="../ethics-toolkit.html">Ethics toolkit</a></nav></header><main>'''+body+'</main><script src="manual.js"></script></body></html>'
 (out/'index.html').write_text(page)
 (out/'manual.js').write_text('''const fields=[...document.querySelectorAll('[data-field]')],key='nspa-protect-manual-v1',status=document.querySelector('#status');function snapshot(){return {format:'nspa-protect-manual-v1',fields:Object.fromEntries(fields.map(e=>[e.id,e.value]))};}function restore(data){if(data.format!==key||!data.fields||typeof data.fields!=='object')throw Error('This is not a saved NSPA PROTECT review.');fields.forEach(e=>{if(typeof data.fields[e.id]==='string')e.value=data.fields[e.id].slice(0,50000);});summarize();}function summarize(){const scores=[...document.querySelectorAll('[data-score]')].map(e=>e.value),rated=scores.filter(v=>['0','1','2'].includes(v));document.querySelector('#progress').textContent=`${scores.filter(v=>v!=='').length} of 7 categories reviewed. ${rated.length?`Entered ratings total ${rated.reduce((s,v)=>s+Number(v),0)} out of ${rated.length*2} possible for rated categories.`:'No numeric ratings entered.'} This is not an approval decision.`;}function save(){try{localStorage.setItem(key,JSON.stringify(snapshot()));status.textContent='Saved in this browser. Export JSON to keep a portable copy.';}catch{status.textContent='Browser storage is unavailable. Export JSON before leaving.';}summarize();}try{const saved=localStorage.getItem(key);if(saved)restore(JSON.parse(saved));}catch{}fields.forEach(e=>e.addEventListener('input',save));summarize();document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{const type=b.dataset.export,rows=fields.map(e=>[e.previousElementSibling.textContent.trim(),e.tagName==='SELECT'?e.selectedOptions[0].text:e.value]);let text=type==='json'?JSON.stringify(snapshot(),null,2):type==='csv'?[['Item','Response'],...rows].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\\n'):'NSPA PROTECT manual review\\n'+document.querySelector('#progress').textContent+'\\n\\n'+rows.map(r=>r.join('\\n')).join('\\n\\n');const u=URL.createObjectURL(new Blob([text],{type:type==='json'?'application/json':type==='csv'?'text/csv':'text/plain'}));const a=document.createElement('a');a.href=u;a.download='nspa-protect-review.'+type;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);status.textContent='Review exported.';});document.querySelector('#import-review').onchange=async e=>{try{restore(JSON.parse(await e.target.files[0].text()));save();}catch(error){status.textContent=error.message;}};addEventListener('beforeprint',()=>fields.forEach(e=>{let p=e.nextElementSibling;if(!p||!p.classList.contains('print-value')){p=document.createElement('p');p.className='print-value';e.after(p);}p.textContent=e.tagName==='SELECT'?e.selectedOptions[0].text:e.value||'No response entered.';}));''')
 return out/'index.html'
if __name__=='__main__':build()
