from content import *
from slides import SLIDES
import html,re
E=html.escape
W=ROOT/'2026'
def shell(title,body,name):
 source=(ROOT/'index.html').read_text()
 head=source.split('<main id="main">')[0]
 head=re.sub(r'<title>.*?</title>',f'<title>{title} | NSPA 2026</title>',head)
 head=head.replace('href="https://mguhlin.github.io/nspa/"',f'href="{URL}{name}"')
 head=head.replace('href="./assets/','href="../assets/').replace('href="./"','href="../"').replace('href="./#library"','href="../#library"').replace('href="./2026/"','href="./"')
 head=head.replace('src="./assets/', 'src="../assets/')
 head=head.replace('</head>','<link rel="stylesheet" href="workshop.css"></head>')
 nav='<nav class="workshop-nav wrap" aria-label="Workshop navigation"><a href="./">Workshop hub</a><a href="practice.html">Practice lab</a><a href="capacity-matrix.html">Capacity matrix</a><a href="./#downloads">Downloads</a></nav>'
 return head+nav+'<main id="main" class="wrap workshop">'+body+'</main><footer class="wrap footer"><p>NSPA 2026 workshop · <a href="https://mguhlin.org">Miguel Guhlin</a></p><p>October 21 · 3:30–5:00 PM CT</p></footer></body></html>'
intro=f'<section class="workshop-title"><p class="eyebrow">NSPA 2026 · October 21 · 3:30–5:00 PM CT</p><h1>Trust, Transparency,<br>and AI</h1><h2>Building Responsible Scholarship Review Practices</h2><p>Build a review prompt, map a protected workflow, and draft a fair approach to applicant AI use.</p><div class="actions"><a class="button" href="practice.html">Open the practice lab →</a><a class="button secondary" href="capacity-matrix.html">My capacity matrix →</a></div></section>'
agenda='<details class="workshop-details"><summary>The 90-minute workshop agenda</summary><div class="table-scroll"><table><thead><tr><th>Time (CT)</th><th>Focus</th><th>What you make</th></tr></thead><tbody>'+''.join(f'<tr><th>{t}<br><small>{d}</small></th><td>{topic}</td><td>{out}</td></tr>' for t,d,topic,out,slides in AGENDA)+'</tbody></table></div></details>'
downloads=[('Presentation','slides/nspa-trust-transparency-ai.pptx','PowerPoint with speaker notes','PPTX'),('Presentation PDF','slides/nspa-trust-transparency-ai.pdf','Easy viewing and sharing','PDF'),('Individual slide images','slides/nspa-trust-transparency-ai-pngs.zip','26 numbered slide PNGs','ZIP'),('Participant workbook','handouts/participant-workbook.pdf','Synthetic packet, rubric, policy lab, and action plan','PDF'),('Facilitator guide','handouts/facilitator-guide.pdf','Timed agenda, demos, debriefs, and offline fallback','PDF'),('Prompt & rubric reference','handouts/prompt-review.pdf','Structure the request and verify the result','PDF'),('Protected workflow reference','handouts/protected-workflow.pdf','Place data approval and human review gates','PDF'),('Fair applicant AI-use reference','handouts/fair-ai-policy.pdf','Interpret concerns and design a fair response','PDF'),('Capacity matrix','handouts/capacity-matrix.pdf','Print the descriptors and mark your next step','PDF')]
dl='<section id="downloads"><p class="eyebrow">Use during the session. Keep afterward.</p><h2>Your workshop materials</h2><div class="download-grid">'+''.join(f'<a class="download" href="{p}"><span class="filetype">{typ}</span><span><strong>{title}</strong><small>{desc}</small></span><span aria-hidden="true">↓</span></a>' for title,p,desc,typ in downloads)+'</div></section>'
refs='<details class="workshop-details"><summary>Quick references as online images</summary><div class="reference-gallery">'
for f,title in [('prompt-review','Prompt & rubric'),('protected-workflow','Protected workflow'),('fair-ai-policy','Fair applicant AI use'),('capacity-matrix-1','Capacity matrix · page 1'),('capacity-matrix-2','Capacity matrix · page 2')]:refs+=f'<a href="images/quick-reference/{f}.png"><img loading="lazy" src="images/quick-reference/{f}.png" alt="{title} quick reference"><strong>{title}</strong></a>'
refs+='</div></details>'
sources='<details class="workshop-details" id="sources"><summary>Sources, interpretation, and reuse</summary><p>Reviewed September 24, 2026. Recheck product guidance before the October workshop. The packet, rubric, policy starter, and capacity matrix are workshop teaching tools, not validated selection instruments or official NSPA policy.</p><ul class="source-list">'+''.join(f'<li><a href="{url}">{title}</a><p>{desc}</p></li>' for title,url,desc in SOURCES)+'</ul><p>All examples are fictional. Use an organization-approved workflow before processing any real applicant data. Policy language needs local review. Generated artwork supports the slides; all instructional wording is separately typeset.</p></details>'
gallery='<details class="workshop-details"><summary>Browse all 26 individual slide images</summary><div class="reference-gallery">'+''.join(f'<a href="images/nspa-trust-transparency-ai/{i:02}.png"><img loading="lazy" src="images/nspa-trust-transparency-ai/{i:02}.png" alt="{E(slide["title"])}"><strong>{i:02}. {E(slide["title"])}</strong></a>' for i,slide in enumerate(SLIDES,1))+'</div><p><a href="slide-transcript.html">Read the slide text and speaker notes</a></p></details>'
(W/'index.html').write_text(shell(TITLE,intro+agenda+dl+refs+gallery+sources,''))
transcript='<p class="eyebrow">Accessible presentation transcript</p><h1>Slide text and speaker notes</h1><p>26 slides in presentation order. Sources appear with the relevant notes.</p>'
for i,slide in enumerate(SLIDES,1):
 transcript+=f'<details class="workshop-details"><summary>{i:02}. {E(slide["title"])}</summary><p>{E(slide["subtitle"])}</p><ul>'+''.join(f'<li><strong>{E(h)}</strong>: {E(t)}</li>' for h,t in slide['blocks'])+f'</ul><p><strong>Your move:</strong> {E(slide["action"])}</p><h2>Speaker notes</h2><p>{E(slide["notes"])}</p>'
 transcript+=''.join(f'<p><a href="{SOURCES[n][1]}">{E(SOURCES[n][0])}</a></p>' for n in slide['sources'])+'</details>'
(W/'slide-transcript.html').write_text(shell('Presentation transcript',transcript,'slide-transcript.html'))
# Practice lab: deterministic copyable content, human reference output and offline activities.
body='<p class="eyebrow">Workshop practice lab</p><h1>Evidence before judgment</h1><p class="lead">Use these fictional materials with an approved Gen AI tool, or complete the activities on paper. No real applicant data is needed.</p><nav class="jump-links" aria-label="Practice sections"><a href="#prompt">Prompt</a><a href="#packet">Packet</a><a href="#rubric">Rubric</a><a href="#policy">Policy</a><a href="#action">Action plan</a></nav>'
def codeblock(id,text):return f'<pre id="{id}">{E(text)}</pre><button type="button" class="button" data-copy="{id}">Copy text</button>'
body+='<section id="prompt"><h2>1. Build a bounded prompt</h2><p>Choose a task. Add criteria, source evidence, boundaries, and a verifiable output format. Ask a partner to find one unsafe assumption.</p>'+codeblock('triage-prompt',PROMPT)+'</section>'
body+='<section id="packet"><h2>2. Test with a synthetic packet</h2><p><strong>Entirely fictional.</strong> Program requirements: enrollment confirmation, a goal statement of no more than 150 words, and one service example. Missing evidence is a follow-up item.</p>'+codeblock('synthetic-packet','\n\n'.join(f'{id}: {text}' for id,text in CASE))+'<details class="workshop-details"><summary>Prepared reference output and verification questions</summary><p>This is an authored teaching reference, not an actual model response. Compare it with a live output or use it offline.</p><table><thead><tr><th>Item</th><th>Status</th><th>Evidence and human check</th></tr></thead><tbody>'+''.join(f'<tr><th>{a}</th><td>{b}</td><td>{c}</td></tr>' for a,b,c in EXPECTED)+'</tbody></table><p>Verify every quote and paragraph ID. Check for invented facts, omitted gaps, and obedience to P5. Record a correction and the human follow-up needed.</p></details></section>'
body+='<section id="rubric"><h2>3. Calibrate the rubric</h2><p>Score independently before comparing with an assistant. Use these training anchors; do not infer merit, authenticity, or personal traits. If the source itself is missing or contradictory, mark “insufficient evidence” and follow up.</p><div class="table-scroll"><table><thead><tr><th>Criterion</th><th>0</th><th>1</th><th>2</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<{tag}>{E(v)}</{tag}>' for tag,v in zip(['th','td','td','td'],row))+'</tr>' for row in RUBRIC)+'</tbody></table></div><p>Compare your evidence and anchor interpretation with a partner. Do not average away disagreement. Revise an ambiguous anchor, then test it again.</p>'+codeblock('rubric-prompt',RUBRIC_PROMPT)+'<details class="workshop-details"><summary>Calibration discussion reference</summary><p>These are defensible teaching judgments, not a validated answer key or award recommendation.</p><ul>'+''.join(f'<li><strong>{a}: {b}.</strong> {c}</li>' for a,b,c in CALIBRATION)+'</ul><p>Keep the first human rating, proposed model rating, final human rating, supporting paragraph, and reason for a change. No overall ranking is needed.</p></details></section>'
body+='<section id="policy"><h2>4. Draft a fair applicant AI-use policy</h2><p><strong>Scenario:</strong> A polished essay is flagged by a detector. The applicant reports translation assistance. The flag and writing style do not establish misconduct. Which published rule applies? What evidence is relevant? What would a neutral request for clarification say?</p>'+codeblock('policy-starter',POLICY)+'<details class="workshop-details"><summary>A neutral follow-up starter</summary><p>“We are reviewing a concern about [specific published requirement] based on [specific evidence]. We have not reached a conclusion. Please explain [relevant point] by [date], or contact [role] for an accessible alternative or additional time. You do not need to share passwords or private chat histories. [Role] will review the information, and [route] explains how to request a further review.”</p><p>Use only when a concern warrants follow-up under the published rules. A detector flag alone does not supply the missing evidence. Resolve policy ambiguity prospectively.</p></details></section>'
body+='<section id="action"><h2>5. Set a 30-day capacity target</h2><p>Choose one task, one owner, one piece of evidence, and one stop condition. Begin with synthetic tests. Consider source errors, omissions, reviewer disagreement, and time spent verifying—not just generation speed.</p><a class="button" href="capacity-matrix.html">Build and export my capacity plan →</a><p><a href="handouts/participant-workbook.pdf">Download the workbook for a paper version</a></p></section><p class="copy-status" role="status" aria-live="polite"></p><script src="practice.js" defer></script>'
(W/'practice.html').write_text(shell('Practice lab',body,'practice.html'))
(W/'practice.js').write_text('''document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const text=document.getElementById(button.dataset.copy).textContent;const status=document.querySelector('.copy-status');try{await navigator.clipboard.writeText(text);status.textContent='Copied. Use only the fictional practice packet.';button.textContent='Copied';setTimeout(()=>button.textContent='Copy text',1800);}catch{status.textContent='Copy is unavailable. Select the text above and copy it manually.';}}));''')
body='<p class="eyebrow">Your workshop capacity matrix</p><h1>Choose your next step</h1><p class="lead">Six capacities for responsible scholarship review. Choose the highest descriptor you can demonstrate in each row. Uneven profiles are normal; this is a self-reflection tool, not a certification.</p><p class="notice">Your ratings and plan stay in this browser’s local storage. Nothing is submitted to a server. Export a copy to keep it; clear the plan on a shared device. Do not enter applicant information.</p><noscript><p>Interactive saving requires JavaScript. Use the <a href="handouts/capacity-matrix.pdf">printable matrix</a> to record your choices.</p></noscript><div class="matrix-wrap"><table class="capacity-table"><caption>From understanding to an evidence-backed team practice</caption><thead><tr><th scope="col">Capacity</th>'+''.join(f'<th scope="col">{i+1}. {level}</th>' for i,level in enumerate(LEVELS))+'</tr></thead><tbody>'
for d in DOMAINS:
 body+=f'<tr><th scope="row"><strong>{E(d["title"])}</strong><small>Evidence: {E(d["evidence"])}</small><div class="matrix-links">'+''.join(f'<a href="{u}">{t} ↗</a>' for t,u in d['links'])+f'</div><button type="button" class="clear-row" data-clear="{d["id"]}">Clear rating</button></th>'
 for i,text in enumerate(d['levels']):body+=f'<td><label><input type="radio" name="{d["id"]}" value="{i+1}" aria-label="{E(d["title"])}: {LEVELS[i]}"><span><b>{LEVELS[i]}</b>{E(text)}</span></label></td>'
 body+='</tr>'
body+='</tbody></table></div><section class="plan-form" aria-labelledby="plan-title"><h2 id="plan-title">My 30-day action plan</h2><p id="matrix-status" role="status" aria-live="polite">No capacities assessed yet.</p><label>Priority capacity<select id="priority"><option value="">Choose a capacity</option>'+''.join(f'<option value="{d["id"]}">{d["title"]}</option>' for d in DOMAINS)+'</select></label><label>My next action<textarea id="next-action" rows="3" maxlength="1500" placeholder="Example: test a completeness prompt on three synthetic packets."></textarea></label><label>Evidence of progress<textarea id="evidence" rows="2" maxlength="1000" placeholder="Example: a corrected table and a log of omissions."></textarea></label><div class="form-row"><label>Owner or role<input id="owner" maxlength="150" placeholder="Example: review lead"></label><label>Target date<input id="target-date" type="date"></label></div><label>Stop condition<textarea id="stop" rows="2" maxlength="1000" placeholder="Example: pause if the tool invents a source quote."></textarea></label><div class="actions"><button class="button" id="export-plan" type="button">Export my plan (.txt)</button><button class="button secondary" id="print-plan" type="button">Print matrix & plan</button><button class="text-button" id="reset-plan" type="button">Clear all saved answers</button></div><p id="save-status" role="status" aria-live="polite"></p></section><script src="capacity-matrix.js" defer></script>'
(W/'capacity-matrix.html').write_text(shell('Capacity matrix',body,'capacity-matrix.html'))
(W/'capacity-data.json').write_text(json.dumps(DOMAINS,indent=2)+'\n')
