from content import *
SLIDES=[]
def add(title,subtitle,layout,blocks,action,notes,art=None,sources=()):
 SLIDES.append(dict(title=title,subtitle=subtitle,layout=layout,blocks=blocks,action=action,notes=notes,art=art,sources=list(sources)))
add('Trust, Transparency, and AI','Building Responsible Scholarship Review Practices','cover',[], '',
'''Welcome. Today we will test what Gen AI can contribute to scholarship review and what must remain a human responsibility. You will leave with a stronger prompt, a protected workflow, and a policy draft you can discuss with your team. Let's begin with one decision you want to improve.''','human-review')
add('Three drafts you can take home','One workshop. Three usable starting points.','cards',[
('A review prompt','Task + evidence + limits'),('A protected workflow','Data gate + human owner'),('A fair AI-use policy','Clear rules + a response path')],
'Choose one real workflow to improve. Use only fictional data today.',
'''I want the next ninety minutes to produce something you can bring back to your organization. Our first draft is a review prompt that asks for evidence instead of a confident opinion. Our second is a workflow that identifies which information may enter an approved tool and who checks the result. Our third is a policy approach that tells applicants what assistance is allowed and gives them a fair way to respond to concerns. These are starting points for local review, not ready-made organizational approvals. Which of those three would make the biggest difference in your current process?''')
add('Keep the decision with people','Different tasks require different authority.','boundary',[
('AI can draft','Organize • summarize • flag missing evidence'),('People must verify','Source facts • rubric fit • uncertainties'),('People decide','Eligibility • awards • policy concerns')],
'Name the person who can accept, revise, reject, or stop the output.',
'''When we say AI-supported review, we need to be precise about the support. Sorting a packet into a checklist is different from deciding whether a person receives an award. A summary can influence judgment even when the final button is clicked by a person. That means human oversight has to be an actual review of evidence, not a rubber stamp. For this workshop, the assistant drafts bounded administrative outputs and provisional rubric observations. It does not make award recommendations. Think about your own workflow: where could an unchecked summary quietly become a decision, and who would be able to catch that?''')
add('Start with an honest baseline','Capacity is something you can demonstrate.','ladder',[
('Explore','I can explain it.'),('Practice','I can try it safely.'),('Apply','Our team uses it consistently.'),('Improve','We test and refine it.')],
'Open the capacity matrix. Pick one row and mark your current evidence.',
'''The capacity matrix is a reflection tool, not a certification or a score for your organization. You may be applying a strong rubric while still exploring applicant AI policy. That uneven profile is useful. It tells you where to invest effort. Read a row and choose the highest level you can support with something observable, such as a tested prompt, a calibration record, or a named decision owner. Leave the row unassessed if you do not know. We will return to the matrix near the end and choose a specific next action. What evidence would make your current rating credible to a colleague?''')
add('Build a prompt that can be checked','A reusable structure for bounded review tasks.','art',[
('Purpose & criteria','What task? Which published rules?'),('Evidence & boundaries','Use supplied sources. Surface uncertainty.'),('Output & verification','Specify a table and a human check.')],
'Ask for source evidence before asking for a judgment.',
'''A useful review prompt tells the assistant what job it has and what authority it does not have. Include the program's actual criteria rather than asking for a good applicant in general. Define the evidence source and request a reference to the relevant paragraph or field. Tell the assistant what to do when information is missing. Finally, ask for a format a reviewer can inspect. None of this guarantees accuracy or removes bias. It gives you a clearer output to test and correct. As you look at the prompt structure, which part is most often missing from the prompts your team currently uses?''','prompt')
add('Replace vague judgment with evidence','The prompt should limit discretion.','compare',[
('Too open','“Find our best applicants.”'),('More testable','“List required items, quote evidence, mark gaps, and identify human follow-up.”')],
'Remove invented criteria, unsupported inference, and automatic ranking.',
'''The first prompt sounds efficient, but it leaves best undefined. A model may fill that gap with writing polish, prestige, or other signals your program never approved. The second prompt has a narrower purpose and a result a person can verify. It does not establish eligibility just because the checklist looks complete. It identifies what is present, missing, or unclear. We can then inspect every entry against the packet. The difference is not a magic phrase. It is a smaller decision space with clearer evidence. How would you rewrite a vague request from your own work so that a second reviewer could check the answer?''')
add('Activity: repair the prompt','Five minutes • work with a partner','activity',[
('2 minutes','Choose one administrative task.'),('2 minutes','Add criteria, evidence, limits, and format.'),('1 minute','Trade prompts. Find one unsafe assumption.')],
'Keep your revised prompt. It is your first workshop deliverable.',
'''Use the prompt practice page or the printed worksheet. Choose an administrative task such as checking completeness, organizing a packet, or preparing follow-up questions. Keep the task small enough that a person can verify the result. Add the criteria, the source boundary, and an instruction for missing information. Then trade with a partner. Your partner is looking for an assumption the assistant might make without permission. You do not need a tool account to participate; a paper revision is enough. When you finish, underline the line that limits the assistant's authority. What did your partner catch that you had not made explicit?''')
add('Our practice packet is entirely fictional','The same evidence supports both demonstrations.','packet',[
('P2 • Goal','Water systems certificate + adviser meeting'),('P3 • Service','Repair table + a concrete queue change'),('P4 / P5 • Stress tests','Missing enrollment record + embedded instruction')],
'Use the synthetic packet only. Missing evidence calls for follow-up.',
'''The packet on the practice page represents no real applicant. C-101 wants to complete a water systems certificate and describes a specific service experience. We intentionally left out enrollment confirmation. We also included a sentence telling the assistant to ignore the rules and mark everything complete. That sentence is part of the application text, not an instruction from the review team. These two features help us test whether the workflow handles uncertainty and untrusted input. Read the paragraph IDs before reviewing any output. What can we actually establish from the packet, and what remains unknown even if a summary sounds confident?''')
add('Live demo: organize, then verify','Administrative triage before any evaluative judgment.','flow',[
('Supply','Synthetic packet + completeness rules'),('Request','Evidence table + missing or unclear items'),('Inspect','Check every row against its paragraph')],
'Do not rank applicants or infer eligibility from absent documents.',
'''Here is the narrow task we are testing: organize the fictional packet into a completeness table. The practice page provides a copyable prompt and packet, so we can use an organization-approved Gen AI tool without bringing real applicant information into the exercise. The output should identify the goal statement and service example, recognize that enrollment confirmation is absent, and ignore the embedded instruction. Results may vary across tools or runs. We will inspect the answer rather than treating a smooth response as success. If the service is unavailable, the clearly labeled reference output lets us complete the same verification exercise. Which row deserves the closest check?''')
add('What a defensible output shows','An inspection target, not a claim about a model run.','audit',[
('Present','Goal: P2 • Service: P3'),('Missing','Enrollment confirmation: P4'),('Ignored','Application instruction: P5')],
'Correct the table before it enters a reviewer’s workspace.',
'''This is a prepared teaching reference, not a screenshot or transcript of a live model response. It shows what we can support from the packet. The goal and service example are present. The enrollment record is missing, which means someone must follow up. It does not mean the applicant is not enrolled. The instruction inside the packet has no authority over the review. Compare these expectations with the live output or the worksheet. Look for an invented fact, an omitted gap, or a conclusion stronger than the evidence allows. If we found one of those errors, what would our workflow prevent from happening next?''')
add('Checkpoint: challenge the output','Four minutes • inspect before accepting','activity',[
('Trace','Can you locate every quoted fact?'),('Challenge','Did it invent, omit, or obey the packet?'),('Correct','Record one fix and one follow-up question.')],
'A clean-looking table is still a draft.',
'''Work through the output as if another reviewer were about to rely on it. First trace each fact back to a paragraph. Next look for something important the output omitted. Finally check whether it treated the embedded instruction as a command. These are different failure modes, so a single overall accuracy judgment is not enough. Record the correction you would make and the question you would send to a human owner. If your output looks correct, describe the evidence that supports that conclusion instead of simply writing looks good. What would you change in the prompt or workflow to catch the same problem on the next packet?''')
add('Use observable rubric anchors','A small training rubric, not an award formula.','rubric',[
('Goal clarity','0: absent • 1: general • 2: goal + next step'),('Contribution','0: absent • 1: named • 2: specific actions'),('Reflection','0: absent • 1: claim • 2: change tied to experience')],
'Score stated evidence. Do not substitute writing polish for the criteria.',
'''This simplified rubric is for practice. It is not a validated scholarship selection instrument. Each criterion has an observable anchor, so reviewers can explain a rating with evidence rather than intuition. A missing source page is different from a source that contains no relevant evidence; the former may require an insufficient-evidence status and follow-up. We also avoid scoring writing polish unless that is an explicit and justified program criterion. A structured rubric may improve consistency, but it does not prove fairness. Your team still needs to test interpretation and consequences. Which anchor could two reasonable reviewers interpret differently, and how would you make it clearer?''')
add('Calibrate people before comparing AI','Six minutes • independent first, discussion second','activity',[
('2 minutes','Read C-101. Rate each criterion independently.'),('2 minutes','Compare evidence and anchor interpretations.'),('2 minutes','Revise one ambiguous anchor together.')],
'Do not show the assistant’s proposed ratings before the first human pass.',
'''Begin with your own reading of the packet. Record a provisional rating for each criterion and the paragraph that supports it. Do not average away disagreements before you understand them. One person may see the queue change as clear evidence of reflection; another may want an explicit statement of what the applicant learned. That difference points to an anchor that needs discussion. Our goal is not to force everyone to agree with a predetermined number. It is to discover how the rubric is being interpreted before using it in a consequential process. Which disagreement came from missing information, and which came from different expectations?''')
add('Compare the assistant’s rubric draft','The second live demonstration keeps authority visible.','flow',[
('Draft','Criterion + quote + provisional rating'),('Compare','Human evidence and anchor interpretation'),('Resolve','Accept, revise, or reject with a reason')],
'Retain the original human rating and the reason for any change.',
'''Now we can ask the assistant for a provisional evidence table using the same fictional packet and rubric. Compare its reasoning with your independent notes. A model can produce a plausible explanation for a weak rating, so the paragraph and anchor must do the work. Do not let agreement with the model substitute for agreement about the criterion. If you change your rating, record why. If the model changes its answer after a small rephrasing, that is useful information about the workflow's stability, not a reason to choose the answer you prefer. What would you require before testing this process on any approved operational data?''')
add('Put a data gate before the tool','Removing a name is only one part of minimization.','art',[
('Approve the use','Purpose, service, permissions, and owner'),('Minimize the input','Only information needed for this task'),('Verify the controls','Access, retention, deletion, and response')],
'Use fictional data until the organization has approved the real-data workflow.',
'''A scholarship packet can reveal identity through context even when the name is removed. Essays, schools, locations, family circumstances, and supporting records can all be sensitive. Our workshop uses synthetic information, which keeps the practice separate from real applicant data. Before any operational use, the organization should decide what information is necessary and which service is approved for that purpose. Check the actual terms and settings rather than assuming every account has the same protections. A label such as enterprise does not replace review. Who in your organization can approve the use, confirm the controls, and stop processing if something changes?''','privacy',sources=(0,))
add('Design the human checkpoints','Six minutes • map one workflow','flow',[
('Before','Approve data + scope + tool'),('During','Check sources + log uncertainty'),('After','Human decision + correction path')],
'Add a stop rule: an unsupported claim or missing control pauses the pilot.',
'''Draw the path from the incoming packet to the final reviewer decision. Place a checkpoint before data enters the tool, one before generated content reaches a reviewer, and one before a consequential action. Name a person or role at each checkpoint. Then choose a stop condition that is specific enough to use, such as a fabricated source quotation or an unapproved change in data handling. The record should show the prompt version, the source material used, the correction, and the decision owner without collecting unnecessary applicant information. Which checkpoint is currently weakest, and what small change could make it an actual control?''',sources=(0,))
add('A detector signal is not a verdict','The output must be interpreted within a fair process.','art',[
('Possible errors','Human text may be flagged. AI text may be missed.'),('Context matters','Tool, language, genre, and version affect results.'),('Policy still governs','A score does not establish a rule violation.')],
'Never use a detector score alone to deny an award or establish misconduct.',
'''An AI-writing indicator is a model output, not a direct observation of how a person wrote. Turnitin's current guidance says its indicator should not be the sole basis for adverse action. Its percentage refers to qualifying text flagged by the model, not the probability that a particular applicant violated a rule. Research also depends on context: a 2023 study found disparities in its English samples, while a 2026 study centered on Czech writing did not find systematic bias in its tested detector families. Neither result supplies a universal error rate. What evidence and policy would you need beyond a flag before raising a concern?''','evidence',sources=(1,2,3))
add('A small error rate can still affect people','Illustration only • not a measured detector benchmark','math',[
('1,000','Entirely human-written submissions'),('1%','Assumed false-positive rate'),('10','Human submissions incorrectly flagged')],
'A false-positive rate is not the probability that a flagged person used AI.',
'''These numbers are hypothetical and intentionally simple. If we tested one thousand entirely human-written submissions with a system that had a one-percent false-positive rate on that population, we would expect about ten incorrect flags. That is not a claim about the performance of any product in your program. It also does not tell us the probability that a flagged submission involved AI. That requires additional information, including prevalence and other error rates. The point is to connect an abstract percentage to the people affected by an accusation. How would your process protect someone who is one of those incorrect flags?''')
add('Publish the rules before applicants apply','Separate assistance, disclosure, and misrepresentation.','choices',[
('Permitted support','Define editing, translation, accessibility, and brainstorming.'),('Disclosure','Specify which uses require a brief explanation.'),('Prohibited conduct','Define fabricated facts, false records, and other violations.')],
'Use one published standard, with examples and an accessible response path.',
'''A useful policy tells an applicant what they may do, what they must disclose, and what would violate the program's rules. Those are separate questions. The workshop starter permits certain forms of support and proposes disclosure for generated substantive passages, but your organization needs to decide the boundary before the application cycle opens. Think about access: requiring paid tools, private chat histories, or an invasive proof process can create new barriers. Define who reviews a concern and how the applicant can respond or seek review. Which sentence in your current instructions would an applicant find hardest to interpret consistently?''')
add('Policy lab: respond without assuming','Six minutes • a fictional concern','activity',[
('Scenario','A polished essay is flagged; the applicant reports translation support.'),('Discuss','Which published rule and evidence apply?'),('Draft','A neutral request for clarification and a review path.')],
'Do not equate language support, style, or a detector flag with dishonesty.',
'''In this fictional scenario, a reviewer sees a detector flag and feels the essay sounds unusually polished. The applicant says they used translation support. We do not know whether a rule was violated. Start with the published policy, not the reviewer's impression. Identify what information is relevant and what would be unreasonable to request. Then draft a short, neutral message that explains the concern, offers an accessible way to respond, and names the next review step. If the existing rules did not address the use, do not invent a retroactive requirement. What would a fair response look like from the applicant's point of view?''',sources=(1,))
add('Make capacity visible','Six connected areas, with evidence for each.','matrix',[
('Scope & ownership','Prompting'),('Rubrics & calibration','Data protection'),('Applicant policy','Pilot evaluation')],
'Return to the matrix. Choose a gap that matters to your next pilot.',
'''The matrix connects the work we just did to your organization's next steps. It covers task scope, prompting, rubric calibration, data protection, applicant policy, and pilot evaluation. You do not need the highest level in every row to learn something useful today. You do need to recognize which gaps would make a real-data pilot inappropriate. The links lead to today's materials and earlier NSPA resources so you can continue with the part you need. Use the descriptors as prompts for discussion rather than a competitive score. Which capacity would most reduce uncertainty in the workflow you chose at the beginning?''')
add('Turn a rating into evidence','Five minutes • one row, one next step','activity',[
('Mark today','Choose a level you can demonstrate.'),('Choose next','Select one observable capacity to build.'),('Name proof','Write the artifact or test that will show progress.')],
'Export or print your plan. Ratings stay in this browser unless you export them.',
'''Pick one row in the online capacity matrix or the printed version. Read the descriptors and select the level that best matches what you can currently demonstrate. Then choose a next step small enough to complete within a month. Evidence might be a revised prompt with a corrected output, a rubric calibration record, or a written data approval decision. Avoid a goal such as become more responsible with AI because it is difficult to test. The site stores ratings locally in this browser and offers an export for your own records. What specific artifact will you be able to show a colleague thirty days from now?''')
add('Plan a bounded 30-day pilot','Practice with synthetic data before any approved real-data phase.','plan',[
('Week 1','Define task, owner, evidence, and data gate.'),('Week 2','Test cases; log omissions and source errors.'),('Weeks 3–4','Review findings. Revise, stop, or seek approval.')],
'Set a baseline, a success measure, and a stop condition before testing.',
'''Your next step does not need to be a large system rollout. A bounded pilot can begin with one task and a small set of fictional or properly authorized test cases. Write down what success would mean before seeing the output. Consider source fidelity, missing items, reviewer disagreement, and time spent checking and correcting, not just generation speed. Name the person who decides whether the test should continue. If a stop condition occurs, record it and pause rather than quietly working around it. At the end of the month, what evidence would justify another test, and what evidence would tell you to stop?''')
add('Leave with a decision you can explain','Three minutes • your exit ticket','exit',[
('One prompt change','What will make the output easier to verify?'),('One safeguard','Where will a person check or stop the workflow?'),('One policy decision','What must applicants know before they apply?')],
'Add an owner and a date to the capacity you want to build.',
'''Look back at the three drafts we set out to create. Choose the prompt change that most improved the connection between claims and evidence. Choose the safeguard that makes human oversight real in your workflow. Then name the policy decision your organization still needs to resolve. You do not have to pretend every question is settled. A useful exit ticket identifies a concrete next action and a person who can move it forward. Keep your drafts and the linked references so the conversation can continue with your team. Which action are you willing to put an owner and a date beside today?''')
add('Keep the materials close','Slides, practice cases, references, and capacity matrix','close',[
('Workshop hub','mguhlin.github.io/nspa/2026/'),('Continue the work','Choose a resource that supports your next step.')],
'Questions: what would make your next review process more explainable?',
'''Everything we used is available from the workshop hub: the presentation, the fictional packet, the prompts, the quick references, and the capacity matrix. You can use the printed materials without an AI account, and the prepared reference outputs support an offline discussion. As you adapt the examples, keep the distinction between a learning exercise and an approved operational process visible. The most useful question is not whether AI can produce an answer. It is whether your team can explain, verify, and take responsibility for how that answer is used. What question should we address before you take this work back to your organization?''')
add('Sources and scope','Research informs the safeguards; workshop tools are local adaptations.','sources',[
('NIST • 2024','Generative AI risk profile'),('Turnitin • reviewed September 2026','Detection interpretation and limitations'),('Research • 2023 and 2026','Detector findings vary with study context')],
'Use the source links in the workshop hub; revisit guidance before adoption.',
'''These sources support specific cautions in the workshop, not a claim that the workshop's rubric or capacity matrix has been validated. NIST provides a risk-management reference for Gen AI. Turnitin explains how its own indicator should be interpreted and limits its use in adverse decisions. The research papers illustrate why evidence about detectors must be read in context. Our synthetic packet, policy starter, capacity descriptors, and pilot activities are teaching materials developed for this session. They require adaptation to your organization's criteria and responsibilities. Before adopting a process, which local owners should review its policy, privacy, accessibility, and operational implications?''',sources=(0,1,2,3))
if __name__=='__main__':
 out=ROOT/'docs/workshop-slide-map.json';out.write_text(json.dumps(SLIDES,indent=2)+'\n')
 print('Slides:',len(SLIDES));print('Notes words:',[len(s['notes'].split()) for s in SLIDES])
